# Generated by Django 2.1.5 on 2020-12-05 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumer',
            old_name='first_name',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='consumer',
            old_name='last_name',
            new_name='reference',
        ),
    ]
